---
title: "Mean centring"
author: "Liam D. Bailey and Martijn van de Pol"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mean centring}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

With an introduction to the basics of the climwin package (see vignette "climwin"), we can start to explore the more advanced features. One feature of particular interest is mean centring. In this vignette we will outline the theory and application of this process, drawing from previous work in van de Pol & Verhulst 2006 [source](http://www.jstor.org/stable/10.1086/503331) and van de Pol & Wright 2009 [source](http://www.sciencedirect.com/science/article/pii/S0003347208005423).

***********************

## The theory

Often when we carry out climate window analysis we possess large biological datasets spanning multiple years, multiple individuals and/or multiple populations. However, when we analyse the effects of climate on our biological response we cannot differentiate between changes occuring within groups (e.g. Year) and changes occuring between groups. Although it is rarely considered, the strength and direction of these effects may differ strongly. Documenting these two effects separately can alter the interpretation of our climate window results.

For example, let's consider we find a strong climate window showing a positive relationship between temperature and a animal body mass. As our data spans multiple years  






```{r}